longhorn:
  defaultSettings:
    defaultReplicaCount: 3
    storageOverProvisioningPercentage: 200
    storageMinimalAvailablePercentage: 25

  ingress:
    enabled: true
    ingressClassName: tailscale
    host: longhorn.${ARGOCD_ENV_DOMAIN}
    tls: true
    tlsSecret: wildcard-tls
    annotations:
      tailscale.com/hostname: "longhorn-nixos-prod"
      tailscale.com/tags: "tag:k8s-ingress,tag:nixos-prod"

  longhornManager:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

  longhornDriver:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

  longhornUI:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

serviceMonitor:
  enabled: true
  labels:
    prometheus: ${ARGOCD_ENV_CLUSTER}
  interval: 30s
  scrapeTimeout: 10s
