server:
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

  ha:
    enabled: true
    replicas: 3

    # Consul backend configuration for HA
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"

        # Enable unauthenticated metrics access (necessary for Prometheus Operator)
        telemetry {
          unauthenticated_metrics_access = "true"
        }
      }

      storage "consul" {
        path = "vault"
        address = "consul-server.consul.svc.cluster.local:8500"
      }

      service_registration "kubernetes" {}

      # Telemetry configuration
      telemetry {
        prometheus_retention_time = "30s"
        disable_hostname = true
      }

  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: longhorn
    accessMode: ReadWriteOnce

  auditStorage:
    enabled: true
    size: 10Gi
    storageClass: longhorn
    accessMode: ReadWriteOnce

ui:
  enabled: true
  serviceType: "ClusterIP"

# Enable service monitor for Prometheus
serverTelemetry:
  serviceMonitor:
    enabled: false  # Set to true once Prometheus Operator is installed
    interval: 30s
    scrapeTimeout: 10s
