apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: personal
  project: app-of-appsets
  source:
    repoURL: https://github.com/santiago-mooser/kubernetes-infrastructure-base.git
    targetRevision: HEAD
    path: common/helm-charts/personal/immich
    directory:
      recurse: true
  syncPolicy: {}