argocd:
  namespace: argocd
  releaseName: argocd

argo-cd:
  redis-ha:
    enabled: false

  repoServer:
    volumes:
      - name: cmp-tmp
        emptyDir: {}

    extraContainers:
      - name: helm-envsubst-plugin
        image: travisghansen/argocd-helm-envsubst-plugin:latest
        command: [/var/run/argocd/argocd-cmp-server]
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - name: var-files
            mountPath: /var/run/argocd
          - name: plugins
            mountPath: /home/argocd/cmp-server/plugins
          - name: cmp-tmp
            mountPath: /tmp

  controller:
    metrics:
      enabled: true
      applicationLabels:
        enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          prometheus: nixos
    replicas: 3
    enableStatefulSet: true
    args:
      statusProcessors: 50
      operationProcessors: 25

  applicationSet:
    replicas: 3
    metrics:
      enabled: true
      applicationLabels:
        enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          prometheus: nixos

  server:
    metrics:
      enabled: true
      applicationLabels:
        enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          prometheus: nixos
    autoscaling:
      enabled: true
      minReplicas: 3
    ingress:
      enabled: true
      ingressClassName: tailscale
      annotations:
        tailscale.com/hostname: "longhorn-nixos-prod"
        tailscale.com/tags: "tag:k8s-ingress,tag:nixos-prod"
      hosts:
        - argocd.nixos.tech.santiago-mooser.com
    extraArgs:
      # Handle TLS on ingress level
      - --insecure
    # Access control for user "developer"

    config:
      exec.enabled: "true"
      ## Plugin: helm-envsubst
      ##
      ## Command:
      ##   - argocd-helm-envsubst-plugin build
      ## Flag:
      ##   - helm-registry-secret-config-path: "repositories.yaml" created by Terraform with gitlab helm resigtry credentials
      ##
      ## Command:
      ##   - argocd-helm-envsubst-plugin render
      ## Flag:
      ##   - log-location: location for writing debug log
      configManagementPlugins: |
        - name: helm-envsubst
          init:
            command: ["sh", "-c"]
            args: ["argocd-helm-envsubst-plugin build"]
          generate:
            command: ["sh", "-c"]
            args: ["argocd-helm-envsubst-plugin render"]

      url: https://argocd.nixos.tech.santiago-mooser.com


  configs:
    kustomize.buildOptions: --enable-alpha-plugins
    params:
      server.insecure: true
      reposerver.parallelism.limit: 20

    cm:
      server.profile.enabled: 'true'
      controller.profile.enabled: 'true'
      exec.enabled: "true"
      timeout.reconciliation: 0s
      resource:
        ignoreResourceUpdatesEnabled: 'false'
        exclusions: |
          - apiGroups:
              - cilium.io
            kinds:
              - CiliumIdentity
            clusters:
              - "*"
        customizations:
          ignoreResourceUpdates.all: |
            jsonPointers:
              - /status
          ignoreResourceUpdates.Pod: |
            jsonPointers:
              - /status
          ignoreResourceUpdates.batch_Job: |
            jsonPointers:
              - /status
          networking.k8s.io/Ingress:
            health.lua: |
              hs = {}
              hs.status = "Healthy"
              return hs
